export default {
    wrapper: {
        alignItems: 'flex-start',
        backgroundColor: 'rgba(0,0,0,.64)',
        display: 'flex',
        height: '100%',
        justifyContent: 'center',
        left: 0,
        overflowY: 'auto',
        position: 'fixed',
        top: 0,
        width: '100%',
        zIndex: 20,
    },
    content: {
        backgroundColor: '#f4f5f7',
        borderRadius: 2,
        margin: '48px 0 80px',
        overflow: 'hidden',
        position: 'relative',
        minWidth: 280,
        maxWidth: '100%',
        zIndex: 25,
        padding: '0 25px',
    },
    header: {
        flex: '0 0 auto',
        padding: '10px 0px',
        position: 'relative',
        minHeight: '20px',
    },
    headerText: {
        overflow: 'hidden',
        overflowWrap: 'break-word',
        padding: '4px 8px',
        margin: 0,
        fontSize: 16,
        color: '#172b4d',
    },
    closeIcon: {
        position: 'absolute',
        right: 0,
        padding: '9px 0px 9px 25px',
        top: 0,
        fontSize: 25,
        color: '#6d6d6d',
        cursor: 'pointer',
    },
    main: {
        marginBottom: 10,
    },
}